---
title: "Learn"
output:
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Learn}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source(here::here('vignettes/setup.R'), local = TRUE)
```

Welcome to the **Learn `r pkg_infos$title` manual**. You will find here full documentation and tutorials for learning to use **`r pkg_infos$title`**.

Before starting using `r pkg_infos$title`, you may be interested in knowing what is [`r pkg_infos$title` about and why `r pkg_infos$title` was created](about.html).

If you are not familiar with `r pkg_infos$title`, have a look at the [Getting started](getting.started.html) page.

# Tutorials

Step-by-step tutorials of how to use `r pkg_infos$title`, in the form of case studies. These tutorials are adapted from training materials originally developed by Epicentre (MSF).

* Prepare a geographic sample

  * [By random sampling of roofs](learn.step.by.step.1.html)
  * [By spatial sampling](learn.step.by.step.2.html)
  * [By spatial sampling supervised](learn.step.by.step.3.html)

For any questions or suggestions, please use the issue tracker: [`r pkg_infos$url_issue`](`r pkg_infos$url_issue`){target="_blank"}.
