---
title: "What is GPS Sampling"
subtitle: >
  What is GPS Sampling, why it was developed and what are the advantages in using it.
output:
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{What is GPS Sampling}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source(here::here('vignettes/setup.R'), local = TRUE) # nolint: undesirable_function_linter.
```

**`r pkg_infos$title`** is a web application designed for providing users with procedures for estimating population size using geographical information. The application is based on [R](https://www.r-project.org/){target="_blank"} freeware and the [Shiny](https://shiny.rstudio.com/){target="_blank"} package.

`r pkg_infos$title` is a fork of [GeoSampler](https://apps.msf.net/geosampler/site/index.html){target="_blank"}, originally developed by [Epicentre](https://epicentre.msf.org/){target="_blank"} to support the activities of [Médecins Sans Frontières](https://www.msf.org){target="_blank"}. This fork is maintained independently for internal use and released under the [WTFPL](http://www.wtfpl.net/){target="_blank"} license.

Please use the issue tracker on GitHub to suggest enhancements or report problems: [`r pkg_infos$url_issue`](`r pkg_infos$url_issue`){target="_blank"}.

Three sampling methods are implemented:

- the [Quadrats]()
- the [T-square]()
- the [Roof-Simple-Random sampling]()

The three methods have different limitations and potential weaknesses depending of the context they are applied and the type and quality of information available.
